server:
  port: 8080

spring:
  application:
    name: cloud-payment-service

  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    # 之前mybatis连的数据库
    #url: jdbc:mysql://localhost:3306/shishi?useUnicode=true&characterEncoding=utf-8&useSSL=false

    # 测camunda连的数据库
    url: jdbc:mysql://localhost:3306/camunda?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

  redis:
    host: localhost
    port: 6379
    timeout: 3000

#可以配置这些就不一一列举了
#  spring.redis.host=127.0.0.1
#  #Redis服务器连接端口
#  spring.redis.port=6379
#  #Redis服务器连接密码（默认为空）
#  spring.redis.password=
#  #连接池最大连接数（使用负值表示没有限制）
#  spring.redis.pool.max-active=8
#  #连接池最大阻塞等待时间（使用负值表示没有限制）
#  spring.redis.pool.max-wait=-1
#  #连接池中的最大空闲连接
#  spring.redis.pool.max-idle=8
#  #连接池中的最小空闲连接
#  spring.redis.pool.min-idle=0
#  #连接超时时间（毫秒）
#  spring.redis.timeout=30000


  # rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#mybatis
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.shishi.beans




#camunda 配置
camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
      first-name: demo
    filter:
      create: All tasks